### ISSUE TITLE
Webscraper additional information is not yet available (e.g, passes are necessary + prices?))

### ISSUE THREAD

**Issue by kajdreef** [TDHTTTT/MESA#10]
At the moment the webscraper only scrapes one page and gets the group lessons time and the class name.
Much information is ignored, like that there are multiple passes (F45, Yoga, GroupX, all access) that each have a different price category. Scraping this information can be useful for the studen We could scrape it separately and add info to the returned task saying: we recommend class: F45 (note: need all access pass or the F45 pass).

**Comment by jessechong** [comment]
For now, let's just use the group lesson time and class name. Don't include what passes are necessary or their prices.

I saw that the pass titles are inside of a <strong> tag. I'm assuming that it wouldn't be too difficult to scrape this information as well. However, like you've said before this is more of a "want" rather than a "need". I'm sure if we really, really, REALLY wanted this later on we could add it on at the end.
